### ISSUE TITLE
bedrock segfaults with imperfect json code

### ISSUE THREAD

**Issue by roblatham00** [mochi-hpc/mochi-bedrock#14]
I set benvolio aside for a while, so I think this json code is out of date but I cannot figure out where the defect lies.

My json file:  https://github.com/mochi-hpc/benvolio/blob/main/tests/bv-bedrock-server.json

My output from bedrock:

```
)% bedrock -v trace -c ../tests/bv-bedrock-server.json tcp
[2023-05-31 17:00:15.642] [trace] Parsing JSON configuration
[2023-05-31 17:00:15.643] [trace] Parsing done
[2023-05-31 17:00:15.643] [trace] Initializing MargoManager
[2023-05-31 17:00:15.643] [trace] Validating JSON configuration
[2023-05-31 17:00:15.643] [trace] Initializing Mercury
[2023-05-31 17:00:15.670] [trace] Initializing Argobots
[2023-05-31 17:00:15.681] [trace] Allocating margo instance
[2023-05-31 17:00:15.681] [trace] Starting progress loop
[2023-05-31 17:00:15.681] [trace] MargoManager initialized
[2023-05-31 17:00:15.681] [trace] Reading Bedrock config
[2023-05-31 17:00:15.681] [trace] Initializing Jx9Manager
[2023-05-31 17:00:15.681] [trace] Initializing Jx9 engine
[2023-05-31 17:00:15.681] [trace] Jx9Manager initialized
[2023-05-31 17:00:15.681] [trace] Initializing ProviderManager
[2023-05-31 17:00:15.681] [trace] ProviderManagerImpl initialized
[2023-05-31 17:00:15.681] [trace] ProviderManager initialized
[2023-05-31 17:00:15.681] [trace] Initializing ClientManager
[2023-05-31 17:00:15.681] [trace] ClientManager initialized
[2023-05-31 17:00:15.681] [trace] Initializing ABTioManager
[2023-05-31 17:00:15.682] [trace] Created ABT-IO instance "abt_io_bv"
[2023-05-31 17:00:15.682] [trace] ABTioManager initialized
[2023-05-31 17:00:15.682] [trace] Initializing MonaManager
[2023-05-31 17:00:15.682] [trace] MonaManager initialized
[2023-05-31 17:00:15.682] [trace] Initialize ModuleContext
[2023-05-31 17:00:15.682] [trace] Loading module benvolio from library libbv-bedrock.so
zsh: segmentation fault (core dumped)  bedrock -v trace -c ../tests/bv-bedrock-server.json tcp
```

I don't actually get a core file but the debugger says the backtrace looks like this:
```
Thread 1 "bedrock" received signal SIGSEGV, Segmentation fault.
bedrock::DynLibServiceFactory::DynLibServiceFactory (this=0x555555588430, moduleName="benvolio", handle=<optimized out>) at /tmp/robl/spack-stage/spack-stage-mochi-bedrock-0.6.2-wvhdzafikatxhb2dk4q2bwqeaypje45n/spack-src/src/DynLibServiceFactory.hpp:54
54      /tmp/robl/spack-stage/spack-stage-mochi-bedrock-0.6.2-wvhdzafikatxhb2dk4q2bwqeaypje45n/spack-src/src/DynLibServiceFactory.hpp: No such file or directory.
(gdb) where
#0  bedrock::DynLibServiceFactory::DynLibServiceFactory (this=0x555555588430, moduleName="benvolio", handle=<optimized out>) at /tmp/robl/spack-stage/spack-stage-mochi-bedrock-0.6.2-wvhdzafikatxhb2dk4q2bwqeaypje45n/spack-src/src/DynLibServiceFactory.hpp:54
#1  0x00007ffff7ebd3f4 in std::_Construct<bedrock::DynLibServiceFactory, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, void*&> (__p=0x555555588430) at /usr/include/c++/12/bits/stl_construct.h:109
#2  std::allocator_traits<std::allocator<void> >::construct<bedrock::DynLibServiceFactory, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, void*&> (__p=0x555555588430) at /usr/include/c++/12/bits/alloc_traits.h:635
#3  std::_Sp_counted_ptr_inplace<bedrock::DynLibServiceFactory, std::allocator<void>, (__gnu_cxx::_Lock_policy)2>::_Sp_counted_ptr_inplace<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, void*&> (__a=..., this=0x555555588420)
    at /usr/include/c++/12/bits/shared_ptr_base.h:604
#4  std::__shared_count<(__gnu_cxx::_Lock_policy)2>::__shared_count<bedrock::DynLibServiceFactory, std::allocator<void>, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, void*&> (__a=..., __p=<optimized out>, this=<optimized out>)
    at /usr/include/c++/12/bits/shared_ptr_base.h:971
#5  std::__shared_ptr<bedrock::DynLibServiceFactory, (__gnu_cxx::_Lock_policy)2>::__shared_ptr<std::allocator<void>, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, void*&> (__tag=..., this=<optimized out>)
    at /usr/include/c++/12/bits/shared_ptr_base.h:1712
#6  std::shared_ptr<bedrock::DynLibServiceFactory>::shared_ptr<std::allocator<void>, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, void*&> (__tag=..., this=<optimized out>) at /usr/include/c++/12/bits/shared_ptr.h:464
#7  std::make_shared<bedrock::DynLibServiceFactory, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, void*&> () at /usr/include/c++/12/bits/shared_ptr.h:1010
#8  bedrock::ModuleContext::loadModule (moduleName="benvolio", library=...) at /tmp/robl/spack-stage/spack-stage-mochi-bedrock-0.6.2-wvhdzafikatxhb2dk4q2bwqeaypje45n/spack-src/src/ModuleContext.cpp:60
#9  0x00007ffff7ebe0f8 in bedrock::ModuleContext::loadModulesFromJSON (jsonString="{\"benvolio\":\"libbv-bedrock.so\"}") at /tmp/robl/spack-stage/spack-stage-mochi-bedrock-0.6.2-wvhdzafikatxhb2dk4q2bwqeaypje45n/spack-src/src/ModuleContext.cpp:84
#10 0x00007ffff7e614ee in bedrock::Server::Server (this=this@entry=0x7fffffff9130, address="tcp",
    configString="{\n\t\"margo\": {\n\t\t\"argobots\":{\n\t\t\t\"__pools_comment\":\"In addition to the traditional progress and rpc pools, Benvolio sets up a third pool for abt-io\",\n\t\t\t\"pools\":[\n\t\t\t\t{\n\t\t\t\t\t\"name\":\"bv_io_pool\"\n\t\t\t\t},\n"...,
    configType=<optimized out>, jx9Params=std::unordered_map with 0 elements) at /tmp/robl/spack-stage/spack-stage-mochi-bedrock-0.6.2-wvhdzafikatxhb2dk4q2bwqeaypje45n/spack-src/src/Server.cpp:130
#11 0x000055555555b38a in main (argc=4, argv=0x7fffffff9e88) at /tmp/robl/spack-stage/spack-stage-mochi-bedrock-0.6.2-wvhdzafikatxhb2dk4q2bwqeaypje45n/spack-src/bin/bedrock.cpp:36
```

**Comment by roblatham00** [comment]
yes, thanks. my --prefix and my LD_LIBRARY_PATH were not the same after all and I was loading a module from March 2022!
